### ISSUE TITLE
Side navigation better suited to left hand side

### ISSUE THREAD

**Issue by Mesuva** [concretecms/documentation.concretecms.org#26]
As discussed in Slack, there's a view that the sidebar navigation being on the right hand side feels strange and is uncommon.

Most online documentation has a sidebar navigation on the left, for comfort and convention.
Typically navigation on the right hand side is used for on-page links only.

Some common examples being:
- https://laravel.com/docs/8.x/
- https://getbootstrap.com/docs/5.0/getting-started/introduction/
- https://v3.vuejs.org/guide/introduction.html
- https://ubuntu.com/server/docs
- https://developer.wordpress.org/themes/

So this is a suggestion to try swapping the menu to the left hand side.
![Screen Shot 2021-12-14 at 11 10 37 am](https://user-images.githubusercontent.com/1079600/146056213-8a83957f-eb1b-4685-9ca1-534af15940b2.png)

**Comment by wordish** [comment]
I think this has been done
